[versions]
kotlin = "2.3.10"
detekt = "2.0.0-alpha.2"
cli = "0.3.6"

[libraries]
cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "cli" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
